### ISSUE TITLE
Bootstrapping the font awesome icons

### ISSUE THREAD

**Issue by joeminicucci** [lucasschejtman/lucasschejtman.github.io#1]
I really like your variation of the Jalpc theme, and I have created my website using it. One quick question: how are you [bootstrapping the social font-awesome icons](https://fontawesome.bootstrapcheatsheets.com/), e.g. Github / LinkedIn in the about section? I didn't notice any references to the FA bootstrap CDN or any local lib / minified copies. I tried adding the same type of icon via the FA cheatsheet codes in my style.css for a pdf symbol linking to my cv, e.g. content:"\f1c1"; with no luck. 

Thanks for the awesome theme!

**Comment by lucasschejtman** [comment]
Hey, have a look at [here](https://github.com/lucasschejtman/lucasschejtman.github.io/blob/master/static/css/style.css#L593) when I'm adding a new font. You can find the actual font [here](https://github.com/lucasschejtman/lucasschejtman.github.io/tree/master/static/fonts)
